services:

  exelens:
    image: image_exelens
    container_name: container_exelens
    build:
      context: ./
      dockerfile: ./build/Dockerfile
      network: host
    volumes:
      - ${FILE_PATH:-./input.file}:/usr/exelens/workdir/input.file:ro
      - ./workdir:/usr/exelens/workdir:rw

  # =====================
  # Testing
  # =====================

  test_unit:
    image: image_exelens_test_unit
    container_name: container_exelens_test_unit
    build:
      context: ./
      dockerfile: ./build/Dockerfile-test
      network: host
    entrypoint: sh -c "pytest -ra ./test/test_unit.py \
      --junitxml=./test/test-results-unit.xml \
      --cov-config=./test/.coveragerc \
      --cov=exelens \
      --cov-report=html:./test/coverage-unit \
      --cov-branch"
    volumes:
      - ./test:/usr/exelens/test:rw
